eng_prp_first = set(['i', 'me', 'mine', 'myself',
    'we', 'us', 'ours', 'ourselves'])
eng_prp_second = set(['you', 'your', 'yours', 'yourself', 'yourselves'])
eng_prp_third = set(['he', 'him', 'his', 'himself', 'she', 'her', 'his', 'herself', 'they', 'them', 'themself', 'themselves'])
eng_punc = set(['!', '.', '?'])

eng_hedge = {
     'almost',
     'apparent',
     'apparently',
     'appear',
     'appeared',
     'appears',
     'approximately',
     'argue',
     'argued',
     'argues',
     'around',
     'assume',
     'assumed',
     'broadly',
     'certain amount',
     'certain extent',
     'certain level',
     'claim',
     'claimed',
     'claims',
     'doubt',
     'doubtful',
     'essentially',
     'estimate',
     'estimated',
     'fairly',
     'feel',
     'feels',
     'felt',
     'frequently',
     'from my perspective',
     'from our perspective',
     'from this perspective',
     'generally',
     'guess',
     'in general',
     'in most cases',
     'in most instances',
     'in my opinion',
     'in my view',
     'in our opinion',
     'in our view',
     'in this view',
     'indicate',
     'indicated',
     'indicates',
     'largely',
     'likely',
     'mainly',
     'may',
     'maybe',
     'might',
     'mostly',
     'often',
     'on the whole',
     'ought',
     'perhaps',
     'plausible',
     'plausibly',
     'possible',
     'possibly',
     'postulate',
     'postulated',
     'postulates',
     'presumable',
     'presumably',
     'probable',
     'probably',
     'quite',
     'rather',
     'relatively',
     'roughly',
     'seems',
     'should',
     'sometimes',
     'somewhat',
     'suggest',
     'suggested',
     'suggests',
     'suppose',
     'supposed',
     'supposes',
     'suspect',
     'suspects',
     'tend to',
     'tended to',
     'tends to',
     'think',
     'thinking',
     'thought',
     'to my knowledge',
     'typical',
     'typically',
     'uncertain',
     'uncertainly',
     'unclear',
     'unclearly',
     'unlikely',
     'usually'
 }
